#!/usr/bin/env python3
"""Generate 64K-token NIAH benchmark for long-context KV eviction experiments.

Creates synthetic Needle-In-A-Haystack items at ~64K tokens by composing
distractor paragraphs with embedded factual needles at controlled positions.

Output: JSONL with {context, question, answer, meta} — compatible with run_v3_jax.py.

Each distractor paragraph is ~80-120 words. For 64K tokens (~49K words) we need
~500 paragraphs. We use the base set with topic-varied transformations to maintain
lexical diversity without trivial repetition.
"""
from __future__ import annotations

import json
import random
import argparse
from pathlib import Path

# ── Base distractor paragraphs (diverse topics, ~80-120 words each) ──────────
# We keep the originals from generate_niah_dataset.py plus add many more.

DISTRACTORS = [
    "The architecture of medieval European cathedrals reflects centuries of evolving engineering "
    "knowledge. Flying buttresses, first used at Notre-Dame de Paris around 1180, transferred "
    "the weight of the roof outward, allowing for thinner walls and larger stained glass windows. "
    "Gothic cathedrals like Chartres and Cologne took decades or even centuries to complete, "
    "involving thousands of skilled craftspeople. The pointed arch, ribbed vault, and flying "
    "buttress together formed the structural vocabulary that defined Gothic architecture across "
    "Europe from the 12th to the 16th century.",

    "The psychology of color perception involves both physical and cultural dimensions. Light "
    "with wavelengths around 620 to 750 nanometers appears red, while 450 to 495 nanometers "
    "appears blue. However, color categories are partly culturally constructed: many languages "
    "lack distinct words for blue and green, grouping them under a single term. The Sapir-Whorf "
    "hypothesis suggests that language influences perception, and studies have shown that speakers "
    "of languages with more color terms can discriminate between similar shades more quickly.",

    "Coffee production is a major global industry, with over 170 million bags produced annually. "
    "Brazil is the world's largest producer, accounting for roughly one-third of global output, "
    "followed by Vietnam, Colombia, and Indonesia. The two main commercial species are Arabica, "
    "which accounts for about 60 percent of production and is considered higher quality, and "
    "Robusta, which is hardier but has a more bitter taste. Coffee plants require specific "
    "growing conditions: altitudes of 600 to 2000 meters, temperatures between 15 and 24 degrees "
    "Celsius, and annual rainfall of 1500 to 3000 millimeters.",

    "The mathematics of fractals, pioneered by Benoit Mandelbrot in the 1970s, describes "
    "self-similar patterns that repeat at every scale. The Mandelbrot set, perhaps the most "
    "famous fractal, is generated by iterating the equation z = z squared plus c for complex "
    "numbers. Fractals appear throughout nature: coastlines, mountain ranges, blood vessel "
    "networks, and tree branching patterns all exhibit fractal properties. The fractal dimension "
    "of the coast of Britain, for example, is approximately 1.25, meaning it is more complex "
    "than a line but less complex than a plane.",

    "Traditional Japanese ceramics encompass a wide range of styles developed over millennia. "
    "Raku ware, associated with the tea ceremony, involves removing pottery from the kiln at "
    "peak temperature and cooling it rapidly, creating unique crack patterns in the glaze. "
    "Kintsugi, the art of repairing broken pottery with gold-laced lacquer, reflects the "
    "philosophy of wabi-sabi, finding beauty in imperfection. The six ancient kilns of Japan, "
    "including Seto, Tokoname, and Bizen, each developed distinctive techniques influenced by "
    "local clay composition and firing methods.",

    "The ecology of coral reef fish communities demonstrates remarkable specialization. Cleaner "
    "fish, such as wrasses and gobies, remove parasites from larger fish at designated cleaning "
    "stations, forming mutualistic relationships. Clownfish live symbiotically with sea anemones, "
    "protected by a mucus coating that prevents the anemone's stinging cells from firing. "
    "Parrotfish play a crucial role in reef health by consuming algae that would otherwise "
    "overgrow and suffocate coral, producing up to 100 kilograms of sand per individual "
    "per year from the coral skeleton they ingest.",

    "The history of cartography reveals how map-making both reflects and shapes worldviews. "
    "The oldest known world map, the Imago Mundi from Babylon, dates to approximately 600 BCE. "
    "Medieval European T-O maps placed Jerusalem at the center, reflecting religious priorities "
    "rather than geographic accuracy. The Mercator projection of 1569 preserved angles for "
    "navigation but dramatically distorted area, making Greenland appear as large as Africa "
    "despite being 14 times smaller. Modern equal-area projections like Peters and Gall-Peters "
    "correct this distortion but introduce their own trade-offs.",

    "Volcanic eruptions can have profound effects on global climate. The 1815 eruption of "
    "Mount Tambora in Indonesia ejected approximately 160 cubic kilometers of material into "
    "the atmosphere, causing the 'Year Without a Summer' in 1816. Sulfur dioxide from the "
    "eruption formed aerosol particles in the stratosphere that reflected sunlight, reducing "
    "global temperatures by 0.4 to 0.7 degrees Celsius. Crop failures across Europe and "
    "North America led to widespread famine.",

    "The acoustics of concert halls depend on complex interactions between sound waves and "
    "architectural surfaces. Reverberation time, the time for sound to decay by 60 decibels, "
    "is a key metric: orchestral halls typically aim for 1.8 to 2.2 seconds, while speech "
    "venues require 0.8 to 1.2 seconds. The Vienna Musikverein, widely considered one of the "
    "finest concert halls, has a reverberation time of approximately 2.0 seconds. The shoebox "
    "shape, narrow and tall with parallel walls, produces strong lateral reflections that "
    "enhance the sense of envelopment and spatial richness of the sound.",

    "The biochemistry of fermentation has been exploited by humans for thousands of years. "
    "Saccharomyces cerevisiae, common baker's and brewer's yeast, converts glucose into "
    "ethanol and carbon dioxide through anaerobic glycolysis. Lactic acid fermentation by "
    "Lactobacillus bacteria produces yogurt, kimchi, and sauerkraut. The pH drop during "
    "lactic fermentation, typically from around 6.5 to 3.5, acts as a natural preservative.",

    "The physics of superconductivity was first observed by Heike Kamerlingh Onnes in 1911 "
    "when he cooled mercury below 4.2 Kelvin. In a superconductor, electrical resistance "
    "drops to exactly zero and magnetic fields are expelled (the Meissner effect). The BCS "
    "theory, developed by Bardeen, Cooper, and Schrieffer in 1957, explains conventional "
    "superconductivity through the formation of Cooper pairs of electrons mediated by phonons. "
    "High-temperature superconductors, discovered in 1986, operate at up to 138 Kelvin.",

    "Urban planning principles have evolved significantly since the early 20th century. "
    "The Garden City movement, proposed by Ebenezer Howard in 1898, envisioned self-contained "
    "communities surrounded by greenbelts, combining the benefits of city and country living. "
    "Le Corbusier's Radiant City concept proposed high-density towers surrounded by parkland, "
    "influencing post-war housing projects worldwide but often criticized for creating "
    "impersonal environments.",

    # --- Additional distractors for 64K diversity ---

    "The development of antibiotics fundamentally transformed medicine in the twentieth century. "
    "Alexander Fleming's accidental discovery of penicillin in 1928 led to the first mass-produced "
    "antibiotic by the early 1940s. During World War II, penicillin saved countless lives by "
    "preventing wound infections. However, antibiotic resistance emerged almost immediately: "
    "penicillin-resistant Staphylococcus strains were documented by 1947. Today, methicillin-resistant "
    "Staphylococcus aureus (MRSA) and extensively drug-resistant tuberculosis represent major "
    "public health threats, prompting urgent searches for novel antimicrobial compounds.",

    "The Silk Road was not a single route but a network of trade paths connecting East Asia "
    "to the Mediterranean. Established during the Han Dynasty around 130 BCE, it facilitated "
    "the exchange of silk, spices, precious metals, and ideas across thousands of miles. "
    "Caravanserais, fortified roadside inns spaced roughly a day's journey apart, provided "
    "shelter for merchants and their animals. Beyond goods, the Silk Road transmitted religions, "
    "technologies, and diseases, including the Black Death, which traveled from Central Asia "
    "to Europe in the fourteenth century.",

    "The theory of plate tectonics, widely accepted since the 1960s, explains the movement "
    "of Earth's lithospheric plates. Alfred Wegener proposed continental drift in 1912, but "
    "his ideas were rejected for decades due to lacking a plausible mechanism. The discovery "
    "of seafloor spreading by Harry Hess in 1962 provided the missing piece. Today, GPS "
    "measurements confirm that plates move at rates of 1 to 15 centimeters per year. The "
    "Pacific Plate, the largest, moves northwest at approximately 7 centimeters annually, "
    "driving volcanism along the Ring of Fire.",

    "The domestication of dogs is one of the oldest examples of artificial selection. Genetic "
    "evidence suggests dogs diverged from wolves between 20,000 and 40,000 years ago, likely "
    "through a process of self-domestication where less fearful wolves scavenged near human "
    "camps. Over millennia, humans bred dogs for specific traits: herding, guarding, hunting, "
    "and companionship. The resulting diversity is extraordinary, from the 2-kilogram Chihuahua "
    "to the 90-kilogram Great Dane, representing more phenotypic variation than exists in any "
    "other single species.",

    "The invention of the printing press by Johannes Gutenberg around 1440 is often cited as "
    "one of the most transformative events in human history. His movable type system allowed "
    "books to be produced far more quickly and cheaply than by hand copying. The Gutenberg "
    "Bible, completed around 1455, was among the first major books printed using this technology. "
    "Within fifty years, an estimated 20 million volumes had been printed across Europe, "
    "democratizing access to knowledge and contributing to the Renaissance, the Reformation, "
    "and the Scientific Revolution.",

    "The chemistry of atmospheric ozone involves a delicate balance of creation and destruction. "
    "In the stratosphere, ultraviolet radiation splits oxygen molecules into atoms, which then "
    "combine with other oxygen molecules to form ozone. This ozone layer absorbs 97 to 99 "
    "percent of harmful UV-B radiation. Chlorofluorocarbons, widely used as refrigerants and "
    "propellants until the 1987 Montreal Protocol, catalytically destroy ozone molecules. "
    "A single chlorine atom can destroy over 100,000 ozone molecules before being deactivated. "
    "The Antarctic ozone hole, first documented in 1985, is slowly recovering.",

    "The economic theory of comparative advantage, formulated by David Ricardo in 1817, "
    "demonstrates that trade can benefit all parties even when one country produces everything "
    "more efficiently than another. The key insight is that nations should specialize in goods "
    "where their relative production costs are lowest. Portugal might produce both wine and "
    "cloth more cheaply than England, but if Portugal's advantage in wine is greater than in "
    "cloth, both nations benefit from Portugal exporting wine and England exporting cloth. "
    "This principle remains foundational to international trade theory.",

    "Quantum entanglement, described by Einstein as 'spooky action at a distance,' is a "
    "phenomenon where two or more particles become correlated in such a way that measuring "
    "one instantaneously determines the state of the other, regardless of the distance "
    "separating them. Bell's theorem, proposed in 1964 and experimentally confirmed multiple "
    "times since, proves that no local hidden variable theory can reproduce all predictions "
    "of quantum mechanics. Modern applications include quantum key distribution for secure "
    "communication and quantum computing architectures.",

    "The Renaissance in Italy, spanning roughly the 14th to the 17th century, represented "
    "a cultural rebirth inspired by the rediscovery of classical Greek and Roman texts. "
    "Florence, under the patronage of the Medici family, became a center of artistic and "
    "intellectual innovation. Artists like Leonardo da Vinci, Michelangelo, and Raphael "
    "developed techniques including linear perspective, chiaroscuro, and anatomical accuracy "
    "that transformed European art. The humanist philosophy that emerged emphasized individual "
    "achievement and the study of classical literature, philosophy, and science.",

    "Deep ocean hydrothermal vents, first discovered in 1977 near the Galapagos Islands, "
    "support ecosystems entirely independent of solar energy. Superheated water, reaching "
    "temperatures up to 400 degrees Celsius, emerges from fissures in the ocean floor, "
    "carrying dissolved minerals that precipitate as chimney-like structures called black "
    "smokers. Chemosynthetic bacteria, which derive energy from hydrogen sulfide, form the "
    "base of these ecosystems, supporting tube worms, giant clams, and eyeless shrimp. "
    "These communities have transformed our understanding of where life can exist.",

    "The Inca Empire, at its height in the early sixteenth century, stretched over 4,000 "
    "kilometers along the western coast of South America. Despite lacking a written language, "
    "the wheel, and iron tools, the Inca built an extensive road network of over 30,000 "
    "kilometers, including suspension bridges across deep gorges. They used quipus, knotted "
    "strings, for record-keeping and accounting. Their agricultural terracing system, still "
    "visible at Moray and other sites, allowed cultivation at high altitudes by creating "
    "microclimate zones at different elevations.",

    "The neuroscience of memory distinguishes between several distinct systems. Declarative "
    "memory, which includes episodic (personal events) and semantic (general knowledge) "
    "memory, depends heavily on the hippocampus. The famous case of patient H.M., who lost "
    "the ability to form new declarative memories after bilateral hippocampal removal, "
    "demonstrated this dependency. Procedural memory, governing skills and habits, relies "
    "instead on the basal ganglia and cerebellum. Working memory, the capacity to hold "
    "information temporarily for manipulation, involves the prefrontal cortex and has "
    "a typical capacity of four to seven items.",

    "The physics of nuclear fusion, the process powering stars, involves forcing light atomic "
    "nuclei together to form heavier ones, releasing enormous energy. In the sun's core, "
    "temperatures of 15 million degrees Celsius and immense pressure fuse hydrogen into "
    "helium, converting mass to energy via Einstein's E=mc squared. Achieving controlled "
    "fusion on Earth requires temperatures exceeding 100 million degrees and magnetic "
    "confinement using tokamak devices. The ITER project in France aims to demonstrate "
    "net energy gain from fusion by the late 2030s, potentially revolutionizing energy.",

    "The art of bookbinding has evolved through numerous techniques over two millennia. "
    "Ancient Romans used wax tablets bound with leather thongs, while the codex format "
    "of folded pages emerged around the first century CE. Medieval monks developed the "
    "practice of coptic binding, which allows books to lie flat when open. The invention "
    "of case binding in the 19th century, where a printed text block is attached to a "
    "pre-made cover, enabled mass production. Japanese stab binding, using decorative "
    "stitching through holes along the spine, represents an elegant alternative tradition.",

    "The sociology of language death documents the disappearance of linguistic diversity. "
    "Of the approximately 7,000 languages spoken today, linguists estimate that over half "
    "will become extinct by the end of this century. Environmental factors, urbanization, "
    "and the dominance of global languages like English, Mandarin, and Spanish drive this "
    "process. The last speaker of Eyak, an Alaskan language, died in 2008. Documentation "
    "efforts using audio recording and written grammars can preserve knowledge of dying "
    "languages, but cannot fully capture the cultural worldview embedded in active use.",

    "The engineering of Roman aqueducts demonstrates sophisticated understanding of hydraulics. "
    "The eleven aqueducts serving ancient Rome delivered approximately one million cubic meters "
    "of water daily, roughly matching the per-capita water supply of modern European cities. "
    "Most of the system ran underground, using gravity-fed channels with a carefully calculated "
    "gradient of about 0.3 meters per kilometer. The famous above-ground arched sections, such "
    "as the Pont du Gard in France, were necessary only where valleys needed to be crossed. "
    "Lead pipes, stone channels, and ceramic tiles served different portions of the network.",

    "The evolution of writing systems spans from pictographs to alphabets over approximately "
    "5,000 years. Sumerian cuneiform, developed around 3400 BCE, used wedge-shaped marks "
    "pressed into clay tablets. Egyptian hieroglyphics, roughly contemporary, combined "
    "logographic and alphabetic elements. The Phoenician alphabet, created around 1050 BCE, "
    "is considered the ancestor of most modern alphabets including Greek, Latin, Arabic, "
    "and Hebrew. Chinese characters represent a separate evolutionary path, with over 50,000 "
    "characters documented, though literacy requires knowledge of about 3,000 to 4,000.",

    "The science of chronobiology studies biological rhythms and their mechanisms. The "
    "circadian clock, located in the suprachiasmatic nucleus of the hypothalamus, generates "
    "approximately 24-hour cycles that regulate sleep, hormone secretion, body temperature, "
    "and metabolism. Light entering the retina signals through the retinohypothalamic tract "
    "to synchronize this internal clock with the external day-night cycle. Disruption of "
    "circadian rhythms through shift work or jet lag is associated with increased risks of "
    "cardiovascular disease, metabolic disorders, and cognitive impairment.",

    "The metallurgy of bronze, an alloy of copper and tin, transformed human civilization "
    "beginning around 3300 BCE. Bronze tools and weapons were harder and more durable than "
    "their copper predecessors, enabling advances in agriculture, warfare, and craftsmanship. "
    "The need for tin, relatively rare compared to copper, drove long-distance trade networks "
    "connecting the mines of Cornwall in Britain and Afghanistan to workshops in Mesopotamia "
    "and Egypt. The transition to iron around 1200 BCE was driven partly by disruptions in "
    "tin supply routes during the Bronze Age Collapse.",

    "The mathematics of cryptography has advanced from simple substitution ciphers to complex "
    "algorithms securing modern digital communication. The Caesar cipher, which shifts each "
    "letter by a fixed number of positions, is easily broken by frequency analysis. The Enigma "
    "machine used in World War II employed rotating mechanical discs to create polyalphabetic "
    "substitutions. Modern public-key cryptography, invented by Diffie and Hellman in 1976, "
    "relies on the computational difficulty of factoring large prime numbers. RSA encryption, "
    "using keys of 2048 bits or more, is considered secure against classical computers.",

    "The biology of photosynthesis converts solar energy into chemical energy through two main "
    "stages. In the light reactions, occurring in the thylakoid membranes, chlorophyll absorbs "
    "photons and uses the energy to split water molecules, producing oxygen and ATP. The Calvin "
    "cycle, occurring in the stroma, uses ATP and NADPH to fix carbon dioxide into glucose. "
    "C4 and CAM photosynthesis represent adaptations to hot, dry climates that minimize "
    "photorespiration. Globally, photosynthesis fixes approximately 100 billion tons of "
    "carbon per year, forming the foundation of nearly all terrestrial food webs.",

    "The philosophy of existentialism, developed primarily in the twentieth century, emphasizes "
    "individual freedom, choice, and responsibility. Jean-Paul Sartre's assertion that 'existence "
    "precedes essence' means that humans are not born with a predetermined nature but create "
    "themselves through their actions. Kierkegaard, often considered the first existentialist, "
    "explored the anxiety of choosing how to live authentically. Heidegger's concept of "
    "Dasein, or 'being-there,' focused on the unique way humans exist in relation to time "
    "and mortality. Camus explored the absurd—the conflict between human desire for meaning "
    "and the universe's apparent indifference.",

    "Glacier dynamics are driven by the balance between accumulation and ablation. Snow "
    "falling in the accumulation zone compresses into firn and eventually ice. When the "
    "weight of accumulated ice exceeds the frictional resistance of the underlying bedrock, "
    "the glacier flows downhill at rates ranging from centimeters to meters per day. "
    "Calving, the breaking off of icebergs at a glacier's terminus, is a major contributor "
    "to mass loss from ice sheets. The Greenland ice sheet alone contains enough frozen "
    "water to raise global sea levels by approximately 7.2 meters if completely melted.",

    "Traditional Chinese medicine operates on principles fundamentally different from Western "
    "biomedicine. The concept of qi, or vital energy, flowing through meridian channels forms "
    "the theoretical basis for acupuncture, which involves inserting fine needles at specific "
    "points to regulate qi flow. Herbal formulations typically combine multiple ingredients "
    "based on their properties of temperature (hot, warm, cool, cold) and flavor (sweet, "
    "sour, bitter, pungent, salty). Tu Youyou's Nobel Prize-winning discovery of artemisinin, "
    "derived from the traditional Chinese herb sweet wormwood, bridges both medical traditions.",

    "The genetics of eye color involves multiple genes interacting in complex ways. The OCA2 "
    "and HERC2 genes on chromosome 15 are the primary determinants, with HERC2 containing "
    "a regulatory element that controls OCA2 expression. Brown eyes result from high melanin "
    "concentration in the iris, while blue eyes result from low melanin and Rayleigh scattering "
    "of light. Green and hazel eyes involve intermediate melanin levels. Contrary to the "
    "simplified model taught in schools, eye color is polygenic, meaning two blue-eyed parents "
    "can occasionally produce a brown-eyed child.",

    "The technology of satellite navigation began with the Transit system developed by the "
    "U.S. Navy in the 1960s for submarine positioning. The modern Global Positioning System "
    "(GPS) uses a constellation of at least 24 satellites orbiting at approximately 20,200 "
    "kilometers altitude. Each satellite broadcasts precise time signals from atomic clocks, "
    "and a receiver calculates its position by measuring signal travel times from at least "
    "four satellites. GPS accuracy has improved from about 100 meters for civilian users in "
    "the 1990s to approximately 30 centimeters with modern dual-frequency receivers.",

    "The ecology of mangrove forests provides critical coastal protection and biodiversity "
    "support. Mangroves, which grow in the intertidal zone of tropical and subtropical "
    "coastlines, have evolved salt-tolerant roots that can filter up to 90 percent of "
    "salt from seawater. Their complex root systems stabilize shorelines, reducing wave "
    "energy by up to 66 percent. Mangrove ecosystems serve as nurseries for many commercially "
    "important fish species and support diverse communities including crabs, mollusks, and "
    "migratory birds. Despite their ecological value, mangroves are being lost at rates "
    "of 1 to 2 percent per year globally.",

    "The study of animal migration reveals extraordinary navigational abilities. Arctic terns "
    "travel approximately 70,000 kilometers annually between Arctic and Antarctic, the longest "
    "known migration of any animal. Monarch butterflies migrate up to 4,800 kilometers from "
    "Canada to central Mexico, guided partly by a sun compass in their antennae. Salmon use "
    "the Earth's magnetic field and olfactory memory of their natal stream's chemical signature "
    "to return to their birthplace after years at sea. Even individual cells of certain species "
    "can detect and respond to magnetic field orientation.",

    "The history of timekeeping reflects humanity's evolving relationship with precision. "
    "Ancient Egyptians divided daylight into twelve segments using sundials around 1500 BCE. "
    "Water clocks, or clepsydrae, provided time measurement independent of sunlight. "
    "Mechanical clocks appeared in European monasteries during the 13th century, initially "
    "accurate only to about 15 minutes per day. The pendulum clock, invented by Christiaan "
    "Huygens in 1656, achieved accuracy of about 10 seconds per day. Modern atomic clocks, "
    "using cesium-133 oscillations, are accurate to within one second over 300 million years.",

    "The chemistry of bioluminescence produces light through enzymatic reactions without heat. "
    "The enzyme luciferase catalyzes the oxidation of the substrate luciferin, producing an "
    "excited-state intermediate that emits a photon as it relaxes to ground state. "
    "Bioluminescence has evolved independently at least 40 times across marine organisms, "
    "insects, fungi, and bacteria. Deep-sea organisms use it for communication, camouflage "
    "through counter-illumination, and predation. The firefly's flash pattern is species-specific "
    "and serves as a mating signal, with some predatory species mimicking the flash patterns "
    "of other species to attract prey.",

    "The anthropology of food reveals how cuisine encodes cultural identity and social "
    "structure. Claude Levi-Strauss's culinary triangle distinguished raw, cooked, and "
    "rotted food as fundamental categories of human culture. Taboos against certain foods, "
    "such as pork in Islam and Judaism, or beef in Hinduism, often have complex historical "
    "and ecological roots beyond simple religious prohibition. The Columbian Exchange after "
    "1492 radically transformed global diets: tomatoes reached Italy, potatoes reached "
    "Ireland, and chili peppers reached India, becoming staples that seem indigenous.",

    "The physics of musical instruments depends on the resonance properties of vibrating "
    "systems. Stringed instruments produce sound by exciting standing waves in stretched "
    "strings, with pitch determined by string length, tension, and mass per unit length. "
    "Wind instruments use vibrating air columns, with open pipes producing all harmonics "
    "and closed pipes producing only odd harmonics. Percussion instruments involve the "
    "vibration of membranes or solid bodies, often producing inharmonic overtones that "
    "give drums and bells their distinctive timbres. The piano is unique in combining both "
    "hammer percussion and string resonance.",

    "The geopolitics of rare earth elements has become increasingly important in the "
    "twenty-first century. These 17 metallic elements, including neodymium, dysprosium, "
    "and lanthanum, are essential for manufacturing permanent magnets in electric motors, "
    "phosphors in display screens, and catalysts in petroleum refining. China produces "
    "approximately 60 percent of global rare earth output and processes over 85 percent. "
    "This concentration has prompted efforts to develop alternative sources in Australia, "
    "Canada, and the United States, as well as recycling technologies and substitute materials.",

    "The psychology of decision-making reveals systematic departures from rational choice. "
    "Kahneman and Tversky's prospect theory, published in 1979, demonstrated that people "
    "evaluate outcomes relative to a reference point and are more sensitive to losses than "
    "to equivalent gains. The framing effect shows that identical choices presented differently "
    "lead to different decisions. The availability heuristic causes people to overestimate "
    "the probability of events that are easily recalled, such as plane crashes versus car "
    "accidents. These cognitive biases have profound implications for economics, policy-making, "
    "and personal financial decisions.",

    "The engineering of suspension bridges requires balancing tensile and compressive forces "
    "across enormous spans. The main cables, typically thousands of steel wires bundled "
    "together, transfer the weight of the deck to the towers through tension. The towers, "
    "in turn, transmit compressive forces to their foundations. The Akashi Kaikyo Bridge "
    "in Japan holds the record for the longest central span at 1,991 meters. Wind resistance "
    "is a critical design factor: the Tacoma Narrows Bridge collapse in 1940, caused by "
    "aeroelastic flutter, demonstrated the danger of inadequate aerodynamic analysis.",

    "The biology of extremophiles challenges our understanding of the limits of life. "
    "Thermophiles thrive at temperatures above 80 degrees Celsius, with some archaea "
    "surviving at 122 degrees in deep-sea vents. Psychrophiles grow optimally below "
    "15 degrees, inhabiting Arctic sea ice and permanently frozen soils. Halophiles "
    "flourish in salt concentrations up to saturation, giving the Dead Sea and salt flats "
    "their characteristic pink color. Radioresistant organisms like Deinococcus radiodurans "
    "can survive radiation doses thousands of times greater than lethal for humans.",

    "The history of vaccination begins with Edward Jenner's observation in 1796 that milkmaids "
    "who had contracted cowpox were immune to smallpox. He inoculated an eight-year-old boy "
    "with cowpox material and later showed the child was protected against smallpox. The word "
    "'vaccine' derives from vacca, Latin for cow. Louis Pasteur extended the principle to other "
    "diseases, developing vaccines for anthrax and rabies in the 1880s. The World Health "
    "Organization's global smallpox vaccination campaign, launched in 1967, achieved the "
    "disease's eradication by 1980, the only human disease ever completely eliminated.",

    "Tidal energy harnesses the predictable movement of ocean waters driven by gravitational "
    "interactions between Earth, Moon, and Sun. The Bay of Fundy in Canada experiences the "
    "world's highest tides, with a range of up to 16 meters. Tidal barrage systems, like the "
    "Rance Tidal Power Station in France (operational since 1966), trap water behind a dam "
    "and release it through turbines. Modern tidal stream generators work like underwater "
    "wind turbines, extracting energy from tidal currents without requiring dams. The "
    "global theoretical potential of tidal energy is estimated at about 3 terawatts.",

    "The mathematics of game theory, formalized by John von Neumann and Oskar Morgenstern "
    "in 1944, analyzes strategic interactions between rational decision-makers. The Nash "
    "equilibrium, introduced by John Nash in 1950, describes a state where no player can "
    "benefit from unilaterally changing strategy. The prisoner's dilemma illustrates how "
    "individually rational decisions can lead to collectively suboptimal outcomes. "
    "Applications range from evolutionary biology, where organisms' strategies evolve "
    "toward Nash equilibria, to auction design, spectrum allocation, and mechanism design "
    "in economics.",

    "The art of Islamic geometric patterns achieves extraordinary complexity through "
    "mathematical precision. Based on repeating units arranged in symmetric tessellations, "
    "these patterns use circles, polygons, and interlacing lines to create the impression "
    "of infinite extension. The Alhambra in Granada, Spain, contains examples of all 17 "
    "possible wallpaper symmetry groups—a mathematical property recognized only in the "
    "nineteenth century. Islamic artisans achieved quasi-crystalline tiling patterns "
    "centuries before the mathematical concept was formalized by Roger Penrose in the 1970s.",

    "The epidemiology of infectious diseases follows predictable mathematical patterns. "
    "The basic reproduction number R0 represents the average number of secondary infections "
    "produced by one infected individual in a fully susceptible population. Measles, one of "
    "the most contagious diseases, has an R0 of 12 to 18, requiring herd immunity thresholds "
    "of 92 to 95 percent. The SIR model, dividing populations into Susceptible, Infected, "
    "and Recovered compartments, captures epidemic dynamics that inform public health "
    "interventions including vaccination campaigns and quarantine strategies.",
]

# ── Needle templates (same as shorter NIAH generator) ─────────────────────────

NEEDLE_TEMPLATES = [
    ("According to an internal memo dated {date}, the recommended activation threshold "
     "for the emergency protocol system is exactly {value}.",
     "What is the recommended activation threshold for the emergency protocol system?",
     "{value}"),

    ("A classified research report identified the optimal resonance frequency "
     "for the acoustic dampening array as precisely {value} hertz.",
     "What is the optimal resonance frequency for the acoustic dampening array?",
     "{value} hertz"),

    ("The chief engineer confirmed that the maximum safe operating pressure "
     "for the primary containment vessel is {value} kilopascals.",
     "What is the maximum safe operating pressure for the primary containment vessel?",
     "{value} kilopascals"),

    ("Internal quality control records show that batch number {value} "
     "was the last one to pass the full certification process before the policy change.",
     "What was the last batch number to pass the full certification process?",
     "{value}"),

    ("The archaeological survey documented that artifact catalog entry {value} "
     "was recovered from the deepest stratum at the excavation site.",
     "What artifact catalog entry was recovered from the deepest stratum?",
     "{value}"),

    ("Navigation logs indicate that the vessel's precise coordinates at the time "
     "of the observation were latitude {value} degrees north.",
     "What was the vessel's latitude at the time of the observation?",
     "{value} degrees north"),

    ("The materials scientist determined that the critical transition temperature "
     "for the new alloy compound is exactly {value} Kelvin.",
     "What is the critical transition temperature for the new alloy compound?",
     "{value} Kelvin"),

    ("According to the census bureau's revised estimate, the population of "
     "the district at the reference date was precisely {value} residents.",
     "What was the population of the district at the reference date?",
     "{value} residents"),

    ("The astronomical observation recorded the angular separation "
     "between the binary star components as {value} arcseconds.",
     "What is the angular separation between the binary star components?",
     "{value} arcseconds"),

    ("The pharmacological trial results confirmed that the effective dose "
     "for the experimental compound is {value} milligrams per kilogram.",
     "What is the effective dose for the experimental compound?",
     "{value} milligrams per kilogram"),
]


def _generate_value(rng: random.Random) -> str:
    style = rng.choice(["code", "decimal", "integer"])
    if style == "code":
        letters = "".join(rng.choices("ABCDEFGHJKLMNPQRSTUVWXYZ", k=3))
        nums = rng.randint(1000, 9999)
        return f"{letters}-{nums}"
    elif style == "decimal":
        return f"{rng.uniform(10, 999):.2f}"
    else:
        return str(rng.randint(100, 99999))


def _generate_date(rng: random.Random) -> str:
    month = rng.choice(["January", "February", "March", "April", "May", "June",
                         "July", "August", "September", "October", "November", "December"])
    day = rng.randint(1, 28)
    year = rng.randint(2018, 2025)
    return f"{month} {day}, {year}"


def build_niah_item(
    rng: random.Random,
    target_context_words: int,
    needle_position: str,
) -> dict:
    """Build one NIAH benchmark item at the specified context length."""
    template_idx = rng.randint(0, len(NEEDLE_TEMPLATES) - 1)
    needle_tmpl, question, answer_tmpl = NEEDLE_TEMPLATES[template_idx]
    value = _generate_value(rng)
    date = _generate_date(rng)
    needle_text = needle_tmpl.format(value=value, date=date)
    answer = answer_tmpl.format(value=value)

    # Build distractor context
    used_distractors = list(DISTRACTORS)
    rng.shuffle(used_distractors)

    paragraphs = []
    word_count = 0

    # First pass: use all unique distractors
    for d in used_distractors:
        paragraphs.append(d)
        word_count += len(d.split())
        if word_count >= target_context_words:
            break

    # If we need more words, cycle through with shuffled order
    while word_count < target_context_words:
        rng.shuffle(used_distractors)
        for d in used_distractors:
            if word_count >= target_context_words:
                break
            paragraphs.append(d)
            word_count += len(d.split())

    # Insert needle at the specified position
    n_paras = len(paragraphs)
    if needle_position == "early":
        insert_idx = max(1, n_paras // 6)
    elif needle_position == "middle":
        insert_idx = n_paras // 2
    else:  # late
        insert_idx = max(1, 5 * n_paras // 6)

    paragraphs.insert(insert_idx, needle_text)
    context = "\n\n".join(paragraphs)

    return {
        "context": context,
        "question": question,
        "answer": answer,
        "meta": {
            "benchmark": "niah_64k",
            "needle_position": needle_position,
            "target_context_words": target_context_words,
            "actual_context_words": len(context.split()),
            "needle_template_idx": template_idx,
            "value": value,
        }
    }


def main():
    parser = argparse.ArgumentParser(description="Generate 64K-token NIAH dataset")
    parser.add_argument("--output", default="data/niah-64k.jsonl")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--items-per-config", type=int, default=20,
                        help="Items per needle position")
    parser.add_argument("--target-words", type=int, default=49000,
                        help="Target context words (~1.3 tokens/word → 64K tokens)")
    args = parser.parse_args()

    rng = random.Random(args.seed)

    # 3 needle positions × N items = total items
    configs = []
    for position in ["early", "middle", "late"]:
        for _ in range(args.items_per_config):
            configs.append((args.target_words, position))

    items = []
    for target_words, position in configs:
        item = build_niah_item(rng, target_words, position)
        items.append(item)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

    total = len(items)
    avg_words = sum(i["meta"]["actual_context_words"] for i in items) / total
    print(f"Generated {total} NIAH items → {out_path}")
    print(f"  Average context: {avg_words:.0f} words (~{avg_words * 1.3:.0f} tokens)")
    for pos in ["early", "middle", "late"]:
        subset = [i for i in items if i["meta"]["needle_position"] == pos]
        avg_w = sum(i["meta"]["actual_context_words"] for i in subset) / len(subset)
        print(f"  {pos}: {len(subset)} items, avg {avg_w:.0f} words")


if __name__ == "__main__":
    main()
